<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_HeatpumpIO" Id="{97d548f3-37ea-4aba-ae88-86175ac4851e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HeatpumpIO
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
IO.bOutputN1 := IO.bInputN1;]]></ST>
    </Implementation>
    <LineIds Name="FB_HeatpumpIO">
      <LineId Id="11" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>