<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_RunningState" Id="{db7d51fb-2638-4812-b81a-d21aedf1ed00}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RunningState IMPLEMENTS I_State
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	pMachine : POINTER TO FB_StateMachine;	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Description" Id="{fff56124-f3e0-4a4a-810d-d034fa66ff15}">
      <Declaration><![CDATA[{warning 'Eigenschaftenimplementierung hinzufügen'}
PROPERTY Description : STRING
]]></Declaration>
      <Get Name="Get" Id="{09f84e37-527b-4c45-880e-5502fab1a5a1}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Description := 'Heat pump is running';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="FB_init" Id="{ccdf553b-48e7-41c3-825a-9b44d85c7b93}">
      <Declaration><![CDATA[//FB_Init ist immer implizit verfügbar und wird primär für die Initialisierung verwendet.
//Der Rückgabewert wird nicht ausgewertet. Für gezielte Einflussnahme können Sie
//die Methoden explizit deklarieren und darin mit dem Standard-Initialisierungscode 
//zusätzlichen Code bereitstellen. Sie können den Rückgabewert auswerten.
METHOD FB_Init: BOOL
VAR_INPUT    
	bInitRetains: BOOL; // TRUE: Die Retain-Variablen werden initialisiert (Reset warm / Reset kalt)    
	bInCopyCode: BOOL;  // TRUE: Die Instanz wird danach in den Kopiercode kopiert (Online-Change)
	pMachine : POINTER TO FB_StateMachine;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.pMachine := pMachine;]]></ST>
      </Implementation>
    </Method>
    <Method Name="HeatIsRequested" Id="{a0b9eadd-22d5-49b2-8876-9665b4185501}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD HeatIsRequested : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="LimitValuesAreExceeded" Id="{ad40b40e-36c5-4eb1-933c-96726184bd4b}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD LimitValuesAreExceeded : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="TargetTemeperatureReached" Id="{5a9d8a2b-41ae-4ad4-8cdf-a0d67cc0af04}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD TargetTemeperatureReached : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="UserPressedConfirmationButton" Id="{34138e8e-29b3-43c6-83b9-21f3a75e6954}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD UserPressedConfirmationButton : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="UserPressedSwitchOffButton" Id="{f7bc4756-a2f3-4317-96b9-0b7e1640f0e8}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD UserPressedSwitchOffButton : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="UserPressedSwitchOnButton" Id="{92d0b6bf-2822-477d-9e93-031fae1f4a37}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD UserPressedSwitchOnButton : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="WaterHasCooledDown" Id="{58ca67bc-c547-44a6-8e50-bdee1b3ac7d1}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD WaterHasCooledDown : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>