<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{e3e9ea5b-aaa6-4abd-9e50-1f99907708dc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbStateMachine				:	FB_StateMachine;
	fbProcessdata				:   FB_Processdata;
	pd 							: 	ST_ProcessData;	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbProcessdata(pd := pd);

fbStateMachine(pd := pd);

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="4" Count="2" />
      <LineId Id="16" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>