<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="convertTimerToDisplayValue" Id="{69bee498-1257-4038-bf88-af12297272dc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION convertTimerToDisplayValue : INT
VAR_IN_OUT
	timerTon		:	TON;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[convertTimerToDisplayValue := TIME_TO_INT ((GVL.configValues.minIdleSec - timerTon.ET) / 1000);
]]></ST>
    </Implementation>
    <LineIds Name="convertTimerToDisplayValue">
      <LineId Id="19" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>