<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ScaleAndRound" Id="{29075e7a-6c68-4092-954a-70806a10ef32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ScaleAndRound : REAL
VAR_INPUT
	realValue 	: REAL;          // Die zu rundende REAL-Zahl
	scaleFactor : INT;           // Rundungsfaktor
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ScaleAndRound := INT_TO_REAL(REAL_TO_INT(realValue * scaleFactor)) / scaleFactor;]]></ST>
    </Implementation>
    <LineIds Name="ScaleAndRound">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>